### ISSUE TITLE
Instructions on how to use tldrstory

### ISSUE THREAD

**Issue by csheargm** [neuml/tldrstory#1]
tldrstory is a great package, it shows the power of AI in a few lines of code. The readme.md file has an installation section, but it would be great to have a step by step instruction on how to set up and run this package. Thank you again for the great package!

**Comment by davidmezzetti** [comment]
Thank you for the nice words and submitting the request. Creating more documentation sounds good. 

Did you have a preferred format in mind for a step-by-step tutorial?

**Comment by csheargm** [comment]
I would say that the readme.md is a great place to start, because people will go to this file first to find out about the package and how to use it.

**Comment by davidmezzetti** [comment]
Sounds good, will put a new section in the README
