### ISSUE TITLE
Can it be used beyond reddit, e.g. providing the own list of headlines?

### ISSUE THREAD

**Issue by robertour** [neuml/tldrstory#2]
Hi @davidmezzetti, 

This looks great, thanks!

I was wondering if is possible to configure this by using my own list of headlines? I can pierce the code if necessary, but a few hints where to start would be great.

**Comment by davidmezzetti** [comment]
Yes, this would be a relatively straightforward change.

I plan on adding the following shortly:

- Read RSS feeds
- Read CSV files
