### ISSUE TITLE
Process is stuck on during API processing

### ISSUE THREAD

**Issue by bryanhaiphanthanh** [neuml/tldrstory#4]
# Summary
Hung terminal after running INDEX_SETTINGS=sports/index.yml API_CLASS=tldrstory.api.API uvicorn "txtai.api:app"

# Steps to reproduce
(this was run on macOS)
1. Install wget via homebrew
`brew install wget`
2. Run the commands from readme.md from https://github.com/neuml/tldrstory

#Expected behavior
As shown in https://github.com/neuml/tldrstory

#Actual behavior 
Everything from 1. Download the “Sports News” application configuration to 2. Start the indexing process works as expected. Terminal is hung after 3, I can type, enter commands, but the process is stuck on step 3. Start the API process. Log is attached below. Note that step 1 and 2 has been run before:
[bugreport1.txt](https://github.com/neuml/tldrstory/files/5460892/bugreport1.txt)

Not sure if of any value, I messed around and entered http://127.0.0.1:8000 into my browser, I received:
<img width="596" alt="Screen Shot 2020-10-29 at 3 51 19 PM" src="https://user-images.githubusercontent.com/61600744/97625220-9ceb8380-19fe-11eb-8e41-2f5acd15bc6a.png">
which prompt me to believe that the terminal is not hung, but the process is just stuck on API processing

#Is this a regression?
No. This issue has been here since the start.

#Debug info
- Streamlit version: Streamlit, version 0.69.2
- Python version: Python 3.7.4
- Using Conda: Conda
- OS version: macOS Catalina version 10.15.6 (19G2021)
- Browser version: Version 86.0.4240.80 (Official Build) (x86_64)

**Comment by bryanhaiphanthanh** [comment]
Problem has been resolved by running API process in the background by adding '&':
`INDEX_SETTINGS=sports/index.yml API_CLASS=tldrstory.api.API uvicorn "txtai.api:app" &`

**Comment by davidmezzetti** [comment]
Glad it's resolved. I added a change to the README to have the API process run in the background.
